#!/usr/bin/env python3
"""
Autonomous Experiment Protocol Generator
Processes Opentrons (.py), Tecan (.xml), and evaluation scripts for autonomous optimization
Generated for Process ID: 22
Template ID: 295
"""

import argparse
import json
import os
import sys
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any

def apply_tecan_unit_conversion(field_name, field_value):
    """Apply Tecan-specific unit conversions based on field type"""
    try:
        # Convert field name to lowercase for easier matching
        field_name_lower = field_name.lower()
        
        # WAVELENGTH CONVERSION: multiply by 10 (nm -> tenths of nm)
        if 'wavelength' in field_name_lower:
            try:
                numeric_value = float(field_value)
                converted_value = int(numeric_value * 10)
                return converted_value
            except (ValueError, TypeError):
                return field_value
        
        # DEFAULT: No conversion needed
        return field_value
            
    except Exception as e:
        return field_value  # Return original value if conversion fails

# Configuration
TEMPLATE_ID = 295
PROCESS_ID = 22

# Protocol files to process
OPENTRONS_FILES = ["Template_295_OT_Protocol_1.py", "Template_295_OT_Protocol_2.py", "Template_295_OT_Protocol_3.py", "Template_295_OT_Protocol_4.py","Template_295_OT_Protocol_5.py","Template_295_OT_Protocol_6.py"]
TECAN_FILES = ["Template_295_TECAN_Protocol_1.xml"]
EVALUATION_SCRIPTS = ["analysis_script_22.py"]

# Individual field mappings (for automated mode compatibility)
OPENTRONS_MAPPINGS = {"[[BUFFER]]": "Buffer", "[[CALIBRATION_CURVE_INTERCEPT]]": "Calibration Curve Intercept", "[[CALIBRATION_CURVE_SLOPE]]": "Calibration Curve Slope", "[[EQUILIBRATION_CYCLES]]": "Equilibration Cycles", "[[EQUILIBRATION_CYCLE_DURATION]]": "Equilibration Cycle Duration", "[[EQUILIBRATION_VOLUME]]": "Equilibration Volume", "[[INCUBATION_TEMPERATURE]]": "Incubation Temperature", "[[INCUBATION_TIME]]": "Incubation Time", "[[LIGAND_CONCENTRATIONS]]": "Ligand concentrations", "[[LIGAND_CONCENTRATION_UNIT]]": "Ligand concentration unit", "[[LIGAND_NAME]]": "Ligand Name", "[[LIGAND_STOCK_CONCENTRATION]]": "Ligand Stock Concentration", "[[MEASUREMENT_VOLUME]]": "Measurement Volume", "[[MEASUREMENT_WAVELENGTH]]": "Measurement Wavelength", "[[NUMBER_OF_LIGAND_CONCENTRATIONS]]": "Number of ligand concentrations", "[[PROCESS_ID]]": "Process ID", "[[PUMP_DURATION]]": "Pump Duration", "[[PUMP_SPEED]]": "Pump Speed", "[[REPLICATES]]": "Replicates", "[[RESIN_MASS]]": "Resin Mass", "[[SHAKER_SPEED_INCUBATION]]": "Shaker Speed Incubation", "[[TOTAL_VOLUME]]": "Total volume", "[[VENTING_TIME]]": "Venting time", "[[WASH_CYCLES]]": "Wash Cycles", "[[WASH_DURATION]]": "Wash Duration", "[[WASH_VOLUME]]": "Wash Volume"}
TECAN_MAPPINGS = {"[[ABSORPTION_WAVELENGTH]]": "Measurement Wavelength"}

def determine_process_mode():
    """Determine if this is an autonomous optimization experiment by checking for required files"""
    # Check if autonomous optimization files exist
    param_file = Path("parameter_combinations.json")
    well_file = Path("well_mapping.json")
    
    return param_file.exists() and well_file.exists()

def load_parameter_combinations():
    """Load parameter combinations from JSON file generated by optimization campaign wizard"""
    param_file = Path("parameter_combinations.json")
    
    if not param_file.exists():
        raise FileNotFoundError(f"Parameter combinations file not found: {param_file}")
    
    print(f"Loading parameter combinations from: {param_file}")
    with open(param_file, 'r') as f:
        parameter_combinations = json.load(f)
    
    # Validate structure
    if not isinstance(parameter_combinations, list):
        raise ValueError("Parameter combinations must be a list")
    
    for i, combo in enumerate(parameter_combinations):
        required_keys = ['combination_id', 'parameters']
        for key in required_keys:
            if key not in combo:
                raise ValueError(f"Parameter combination {i} missing required key: {key}")
    
    print(f"Successfully loaded {len(parameter_combinations)} parameter combinations")
    return parameter_combinations

def load_well_mapping():
    """Load well mapping from JSON file generated by optimization campaign wizard"""
    well_file = Path("well_mapping.json")
    
    if not well_file.exists():
        raise FileNotFoundError(f"Well mapping file not found: {well_file}")
    
    print(f"Loading well mapping from: {well_file}")
    with open(well_file, 'r') as f:
        well_mapping = json.load(f)
    
    # Validate structure
    if not isinstance(well_mapping, list):
        raise ValueError("Well mapping must be a list")
    
    for i, mapping in enumerate(well_mapping):
        required_keys = ['combination_id', 'wells', 'replicate_count']
        for key in required_keys:
            if key not in mapping:
                raise ValueError(f"Well mapping {i} missing required key: {key}")
    
    print(f"Successfully loaded {len(well_mapping)} well mappings")
    return well_mapping

def process_autonomous_opentrons_file(filename, parameter_combinations, well_mapping):
    """Process Opentrons file for autonomous optimization"""
    protocols_folder = Path("protocols")
    file_path = protocols_folder / filename
    
    if not file_path.exists():
        return {}
    
    print(f"Processing Opentrons file for autonomous optimization: {filename}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    replacements_made = {}
    
    # Replace [[PARAMETER_COMBINATIONS]] placeholder
    if "[[PARAMETER_COMBINATIONS]]" in content:
        combinations_json = json.dumps(parameter_combinations, indent=4)
        content = content.replace("[[PARAMETER_COMBINATIONS]]", combinations_json)
        replacements_made["[[PARAMETER_COMBINATIONS]]"] = f"{len(parameter_combinations)} combinations"
        print(f"  Replaced [[PARAMETER_COMBINATIONS]] with {len(parameter_combinations)} combinations")
    
    # Replace [[WELL_MAPPING]] placeholder
    if "[[WELL_MAPPING]]" in content:
        well_mapping_json = json.dumps(well_mapping, indent=4)
        content = content.replace("[[WELL_MAPPING]]", well_mapping_json)
        replacements_made["[[WELL_MAPPING]]"] = f"{len(well_mapping)} mappings"
        print(f"  Replaced [[WELL_MAPPING]] with {len(well_mapping)} well mappings")
    
    # Write back to file
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return replacements_made

def process_autonomous_tecan_file(filename, parameter_combinations, well_mapping):
    """Process Tecan file for autonomous optimization"""
    protocols_folder = Path("protocols")
    file_path = protocols_folder / filename
    
    if not file_path.exists():
        return {}
    
    print(f"Processing Tecan file for autonomous optimization: {filename}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    replacements_made = {}
    
    # For Tecan XML files, we typically need to replace measurement parameters
    # but maintain the parameter combinations structure in comments or metadata
    
    # Add parameter combinations as XML comment for reference
    if parameter_combinations:
        param_comment = f"<!-- Parameter Combinations: {json.dumps(parameter_combinations, indent=2)} -->"
        content = param_comment + "\n" + content
        replacements_made["parameter_combinations_comment"] = f"{len(parameter_combinations)} combinations added as comment"
    
    # Replace any Tecan-specific placeholders using loaded mappings
    tecan_mappings = load_tecan_mappings()
    for placeholder, field_name in tecan_mappings.items():
        if placeholder in content:
            # For autonomous mode, we might need to use a default value or the first combination's value
            if parameter_combinations:
                first_combo_params = parameter_combinations[0]["parameters"]
                if field_name in first_combo_params:
                    value = first_combo_params[field_name]
                    content = content.replace(placeholder, str(value))
                    replacements_made[placeholder] = value
                    print(f"  Replaced {placeholder} -> {value} (from first combination)")
    
    # Write back to file
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return replacements_made

def process_evaluation_script(filename, parameter_combinations, well_mapping, experiment_id):
    """Process evaluation script to include parameter combinations and well mapping"""
    analysis_folder = Path("../analysis")  # Evaluation scripts are typically in analysis folder
    file_path = analysis_folder / filename
    
    if not file_path.exists():
        print(f"  Warning: Evaluation script not found: {file_path}")
        return {}
    
    print(f"Processing evaluation script: {filename}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    replacements_made = {}
    
    # Create optimization data structure for the evaluation script
    optimization_data = {
        "experiment_id": experiment_id,
        "parameter_combinations": parameter_combinations,
        "well_mapping": well_mapping,
        "generated_timestamp": datetime.utcnow().isoformat()
    }
    
    # Save optimization data to a JSON file that the evaluation script can load
    data_file_path = Path("../data") / f"optimization_data_{experiment_id}.json"
    data_file_path.parent.mkdir(exist_ok=True)
    
    with open(data_file_path, 'w') as f:
        json.dump(optimization_data, f, indent=2)
    
    replacements_made["optimization_data_file"] = str(data_file_path)
    
    # If the evaluation script has placeholders, replace them
    if "[[PARAMETER_COMBINATIONS]]" in content:
        combinations_json = json.dumps(parameter_combinations, indent=4)
        content = content.replace("[[PARAMETER_COMBINATIONS]]", combinations_json)
        replacements_made["[[PARAMETER_COMBINATIONS]]"] = f"{len(parameter_combinations)} combinations"
    
    if "[[WELL_MAPPING]]" in content:
        well_mapping_json = json.dumps(well_mapping, indent=4)
        content = content.replace("[[WELL_MAPPING]]", well_mapping_json)
        replacements_made["[[WELL_MAPPING]]"] = f"{len(well_mapping)} mappings"
    
    # Replace experiment ID placeholder if present
    if "[[EXPERIMENT_ID]]" in content:
        content = content.replace("[[EXPERIMENT_ID]]", str(experiment_id))
        replacements_made["[[EXPERIMENT_ID]]"] = experiment_id
    
    # Write back to file
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"  Created optimization data file: {data_file_path}")
    
    return replacements_made

def load_tecan_mappings():
    """Return embedded Tecan field mappings"""
    return TECAN_MAPPINGS

def process_automated_file(filename, experiment_data, mappings, file_type="opentrons"):
    """Process file using automated mode (individual placeholder replacement)"""
    if file_type == "opentrons":
        protocols_folder = Path("protocols")
    else:
        protocols_folder = Path("protocols")
    
    file_path = protocols_folder / filename
    
    if not file_path.exists():
        return {}
    
    print(f"Processing {file_type} file (automated mode): {filename}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    replacements = replace_placeholders(content, experiment_data, mappings)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(replacements["content"])
    
    return replacements["replacements"]

def replace_placeholders(content, experiment_data, mappings):
    """Replace individual placeholders in content with experiment values (automated mode)"""
    metadata = experiment_data.get('metadata_decoded', {})
    extra_fields = metadata.get('extra_fields', {})
    
    replaced_content = content
    replacements_made = {}
    
    for placeholder, field_name in mappings.items():
        if field_name in extra_fields:
            field_value = extra_fields[field_name].get('value', '')
            if field_value:
                # Apply Tecan wavelength conversion (×10 for nm -> tenths of nm)
                converted_value = apply_tecan_unit_conversion(field_name, field_value)
                replaced_content = replaced_content.replace(placeholder, str(converted_value))
                replacements_made[placeholder] = converted_value
                if converted_value != field_value:
                    print(f"  Replaced {placeholder} -> {converted_value} (converted from {field_value})")
                else:
                    print(f"  Replaced {placeholder} -> {field_value}")
        else:
            print(f"  Warning: Field '{field_name}' not found for {placeholder}")
    
    return {"content": replaced_content, "replacements": replacements_made}

def generate_protocols_for_experiment(experiment_id):
    """Main function: Process files based on autonomous vs automated mode"""
    print(f"Processing experiment {experiment_id}...")
    
    # Load experiment data
    with open(f"experiment_{experiment_id}.json", 'r') as f:
        experiment_data = json.load(f)
    
    # Determine processing mode by checking for autonomous data files
    is_autonomous = determine_process_mode()
    
    all_replacements = {}
    modified_files = []
    
    if is_autonomous:
        print("🎯 AUTONOMOUS MODE: Loading parameter combinations and well mapping from files")
        
        try:
            # Load parameter combinations and well mapping from JSON files
            parameter_combinations = load_parameter_combinations()
            well_mapping = load_well_mapping()
            
            print(f"Loaded {len(parameter_combinations)} parameter combinations")
            print(f"Loaded {len(well_mapping)} well mappings")
            
            # Validate consistency between parameter combinations and well mapping
            param_ids = {combo['combination_id'] for combo in parameter_combinations}
            mapping_ids = {mapping['combination_id'] for mapping in well_mapping if mapping['combination_id'] >= 0}  # Exclude controls
            
            missing_mappings = param_ids - mapping_ids
            if missing_mappings:
                print(f"⚠️  Warning: Parameter combinations without well mappings: {missing_mappings}")
            
            extra_mappings = mapping_ids - param_ids
            if extra_mappings:
                print(f"⚠️  Warning: Well mappings without parameter combinations: {extra_mappings}")
            
        except (FileNotFoundError, ValueError) as e:
            print(f"❌ Error loading autonomous data files: {e}")
            print("Falling back to automated mode...")
            is_autonomous = False
    
    if is_autonomous:
        # Process Opentrons files (autonomous mode)
        for filename in OPENTRONS_FILES:
            replacements = process_autonomous_opentrons_file(filename, parameter_combinations, well_mapping)
            all_replacements.update(replacements)
            if replacements:
                modified_files.append(f"protocols/{filename}")
        
        # Process Tecan files (autonomous mode)
        for filename in TECAN_FILES:
            replacements = process_autonomous_tecan_file(filename, parameter_combinations, well_mapping)
            all_replacements.update(replacements)
            if replacements:
                modified_files.append(f"protocols/{filename}")
        
        # Process evaluation scripts
        for filename in EVALUATION_SCRIPTS:
            replacements = process_evaluation_script(filename, parameter_combinations, well_mapping, experiment_id)
            all_replacements.update(replacements)
            if replacements:
                modified_files.append(f"analysis/{filename}")
        
        # Save autonomous experiment data for reference
        autonomous_data = {
            "experiment_id": experiment_id,
            "mode": "autonomous",
            "parameter_combinations_file": "parameter_combinations.json",
            "well_mapping_file": "well_mapping.json",
            "parameter_combinations_count": len(parameter_combinations),
            "well_mappings_count": len(well_mapping),
            "timestamp": datetime.utcnow().isoformat()
        }
        
        with open(f"autonomous_experiment_{experiment_id}.json", 'w') as f:
            json.dump(autonomous_data, f, indent=2)
        
        print(f"✅ Autonomous experiment log saved to: autonomous_experiment_{experiment_id}.json")
        
    else:
        print("🔧 AUTOMATED MODE: Individual placeholder replacement")
        
        # Process Opentrons files (automated mode)
        for filename in OPENTRONS_FILES:
            replacements = process_automated_file(filename, experiment_data, OPENTRONS_MAPPINGS, "opentrons")
            all_replacements.update(replacements)
            if replacements:
                modified_files.append(f"protocols/{filename}")
        
        # Process Tecan files (automated mode)
        for filename in TECAN_FILES:
            replacements = process_automated_file(filename, experiment_data, TECAN_MAPPINGS, "tecan")
            all_replacements.update(replacements)
            if replacements:
                modified_files.append(f"protocols/{filename}")
    
    # Save log
    log_data = {
        "experiment_id": experiment_id,
        "mode": "autonomous" if is_autonomous else "automated",
        "timestamp": datetime.utcnow().isoformat(),
        "replacements_made": all_replacements,
        "modified_files": modified_files,
        "template_id": TEMPLATE_ID,
        "process_id": PROCESS_ID,
        "autonomous_data": {
            "parameter_combinations_count": len(parameter_combinations) if is_autonomous else 0,
            "well_mappings_count": len(well_mapping) if is_autonomous else 0,
            "data_files_found": is_autonomous
        }
    }
    
    with open("protocol_generation_log.json", 'w') as f:
        json.dump(log_data, f, indent=2)
    
    mode_str = "AUTONOMOUS" if is_autonomous else "AUTOMATED"
    print(f"✅ {mode_str} processing complete! {len(all_replacements)} replacements in {len(modified_files)} files")
    
    return {
        "success": True,
        "mode": "autonomous" if is_autonomous else "automated",
        "replacements": all_replacements,
        "modified_files": modified_files,
        "opentrons_files_processed": len([f for f in OPENTRONS_FILES if f"protocols/{f}" in modified_files]),
        "tecan_files_processed": len([f for f in TECAN_FILES if f"protocols/{f}" in modified_files]),
        "evaluation_scripts_processed": len([f for f in EVALUATION_SCRIPTS if f"analysis/{f}" in modified_files]) if is_autonomous else 0,
        "data_files_loaded": is_autonomous
    }

def main():
    """Command line interface"""
    parser = argparse.ArgumentParser(
        description='Generate experiment-specific protocols from templates (supports both automated and autonomous modes)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"""
Examples:
  python {os.path.basename(__file__)} --experiment-id 3914
  python {os.path.basename(__file__)} --experiment-id 3914 --verbose

Modes:
  AUTOMATED: Individual placeholder replacement (e.g., [[TEMPERATURE]] -> 25.0)
  AUTONOMOUS: Uses parameter_combinations.json & well_mapping.json for optimization campaigns

Required Files for Autonomous Mode:
  - parameter_combinations.json: Generated by optimization campaign wizard
  - well_mapping.json: Generated by optimization campaign wizard
  - experiment_.json: eLabFTW experiment data

Configuration:
  Template ID: {TEMPLATE_ID}
  Process ID: {PROCESS_ID}
  Opentrons files: {len(OPENTRONS_FILES)}
  Tecan files: {len(TECAN_FILES)}
  Evaluation scripts: {len(EVALUATION_SCRIPTS)}
        """
    )
    parser.add_argument('--experiment-id', required=True, type=int,
                       help='eLabFTW experiment ID')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Enable verbose output')
    parser.add_argument('--mode', choices=['auto', 'automated', 'autonomous'],
                       default='auto', help='Force processing mode (default: auto-detect)')
    parser.add_argument('--check-files', action='store_true',
                       help='Check for required autonomous files and exit')
    
    args = parser.parse_args()
    
    # Handle --check-files option
    if args.check_files:
        print(f"🔍 Checking for autonomous mode files...")
        param_file = Path("parameter_combinations.json")
        well_file = Path("well_mapping.json")
        exp_file = Path(f"experiment_{args.experiment_id}.json")
        
        print(f"parameter_combinations.json: {'✅ Found' if param_file.exists() else '❌ Missing'}")
        print(f"well_mapping.json: {'✅ Found' if well_file.exists() else '❌ Missing'}")
        print(f"experiment_{args.experiment_id}.json: {'✅ Found' if exp_file.exists() else '❌ Missing'}")
        
        if param_file.exists() and well_file.exists() and exp_file.exists():
            print("\n🎯 All files found - ready for AUTONOMOUS mode")
            return 0
        elif exp_file.exists():
            print("\n🔧 Only experiment file found - will use AUTOMATED mode")
            return 0
        else:
            print(f"\n❌ Missing required files for experiment {args.experiment_id}")
            return 1
    
    if args.verbose:
        print(f"🧪 Autonomous Experiment Generator Script")
        print(f"Template ID: {TEMPLATE_ID}")
        print(f"Process ID: {PROCESS_ID}")
        print(f"Opentrons files: {OPENTRONS_FILES}")
        print(f"Tecan files: {TECAN_FILES}")
        print(f"Evaluation scripts: {EVALUATION_SCRIPTS}")
        print(f"Mode: {args.mode}")
        
        # Check for autonomous data files
        param_file_exists = Path("parameter_combinations.json").exists()
        well_file_exists = Path("well_mapping.json").exists()
        print(f"parameter_combinations.json: {'✅ Found' if param_file_exists else '❌ Missing'}")
        print(f"well_mapping.json: {'✅ Found' if well_file_exists else '❌ Missing'}")
        
        if param_file_exists and well_file_exists:
            print("🎯 Will run in AUTONOMOUS mode")
        else:
            print("🔧 Will run in AUTOMATED mode")
        
        print("-" * 50)
    
    try:
        result = generate_protocols_for_experiment(args.experiment_id)
        
        if result["success"]:
            mode_icon = "🎯" if result["mode"] == "autonomous" else "🔧"
            print(f"\n✅ Success! {mode_icon} {result['mode'].upper()} MODE")
            print(f"   Experiment ID: {args.experiment_id}")
            print(f"   Replacements made: {len(result['replacements'])}")
            print(f"   Opentrons files processed: {result['opentrons_files_processed']}")
            print(f"   Tecan files processed: {result['tecan_files_processed']}")
            if result["mode"] == "autonomous":
                print(f"   Evaluation scripts processed: {result['evaluation_scripts_processed']}")
                print(f"   Data files loaded: {'✅ Yes' if result['data_files_loaded'] else '❌ No'}")
            print(f"   Modified files: {len(result['modified_files'])}")
            
            if args.verbose:
                print(f"\n📝 Details:")
                for placeholder, value in result['replacements'].items():
                    print(f"   {placeholder} → {value}")
            
            return 0
        else:
            print(f"\n❌ Failed to process experiment {args.experiment_id}")
            return 1
            
    except FileNotFoundError as e:
        error_message = str(e)
        print(f"\n❌ Error: Required file not found")
        
        if "parameter_combinations.json" in error_message:
            print(f"   Missing: parameter_combinations.json (required for autonomous mode)")
            print(f"   This file should be generated by the optimization campaign wizard")
        elif "well_mapping.json" in error_message:
            print(f"   Missing: well_mapping.json (required for autonomous mode)")
            print(f"   This file should be generated by the optimization campaign wizard")
        elif f"experiment_{args.experiment_id}.json" in error_message:
            print(f"   Missing: experiment_{args.experiment_id}.json (eLabFTW experiment data)")
            print(f"   Make sure the experiment data has been exported from eLabFTW")
        else:
            print(f"   Details: {e}")
        
        print(f"\n💡 Tip: Use --check-files to verify all required files exist")
        return 1
    except Exception as e:
        print(f"\n❌ Error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

if __name__ == '__main__':
    sys.exit(main())